// ============================================================================
// Native AOT scenario tracked by the AOT-size regression check.
//
// The published binary's file size is recorded per-RID in
// aot-size-baselines.json (next to this file) and compared on every CI run
// by `make test-aot-size` (see eng/AotSizeCheck and .github/workflows/build.yml).
//
// DO NOT EDIT THIS FILE CASUALLY. The model below intentionally exercises a
// representative cross-section of every PolyType shape kind (primitive bag,
// nullable, enum, list, dictionary, set, union with DerivedTypeShape,
// surrogate with TypeShape(Marshaler=...)) so that a regression in the
// PolyType core, the source generator, or PolyType.Examples is reflected in
// the measured app size. The goal is a stable canary, not a realistic
// scenario: any addition or removal of shape kinds, or any change to the
// shape graph reachable from ShapeShowcase, will shift the measured size on
// every supported platform and force every committed baseline to be
// re-generated. Treat changes here the same way you would treat changes to
// a perf benchmark.
// ============================================================================

using System.Globalization;
using PolyType;
using PolyType.Examples.JsonSerializer;

ShapeShowcase sample = new(
    Primitives: new PrimitiveBag(IntValue: 42, StringValue: "hello", BoolValue: true, Decimal: 3.14m),
    Color: Color.Green,
    OptionalInt: 7,
    Numbers: [1, 2, 3, 4, 5],
    Lookup: new Dictionary<string, double>
    {
        ["pi"] = 3.14,
        ["e"] = 2.72,
    },
    Tags: new HashSet<string> { "alpha", "beta", "gamma" },
    Pet: new Cat(Name: "Whiskers", Indoor: true),
    Id: new Identifier("urn", 99));

string json = JsonSerializerTS.Serialize(sample);
Console.WriteLine($"serialized: {json}");

ShapeShowcase? roundTripped = JsonSerializerTS.Deserialize<ShapeShowcase>(json);
Console.WriteLine(roundTripped is null ? "deserialized: null" : "deserialized: ok");

[GenerateShape]
public partial record ShapeShowcase(
    PrimitiveBag Primitives,
    Color Color,
    int? OptionalInt,
    List<int> Numbers,
    Dictionary<string, double> Lookup,
    HashSet<string> Tags,
    Pet Pet,
    Identifier Id);

public record PrimitiveBag(int IntValue, string? StringValue, bool BoolValue, decimal Decimal);

public enum Color { Red, Green, Blue }

[DerivedTypeShape(typeof(Cat))]
[DerivedTypeShape(typeof(Dog))]
public abstract record Pet(string Name);

public sealed record Cat(string Name, bool Indoor) : Pet(Name);

public sealed record Dog(string Name, string Breed) : Pet(Name);

[TypeShape(Marshaler = typeof(Marshaler))]
public record Identifier(string Scheme, int Value)
{
    public sealed class Marshaler : IMarshaler<Identifier, string>
    {
        public string? Marshal(Identifier? value)
            => value is null ? null : $"{value.Scheme}:{value.Value.ToString(CultureInfo.InvariantCulture)}";

        public Identifier? Unmarshal(string? value)
        {
            if (value is null)
            {
                return null;
            }

            int separator = value.IndexOf(':');
            return new Identifier(
                value[..separator],
                int.Parse(value[(separator + 1)..], CultureInfo.InvariantCulture));
        }
    }
}
